version: '3'
services:
  app:
    build: .
    container_name: 'app'
    environment:
      - API_KEY
    volumes:
      - ./app:/app

  nginx:
    container_name: 'nginx'
    image: 'nginx'
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - 80:80
