version: '3'
services:
  app:
    build: .
    container_name: 'app'
    environment:
      - API_KEY
    volumes:
      - ./src:/app
      - ./static:/static
    stdin_open: true

  nginx:
    container_name: 'nginx'
    image: 'nginx'
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./static:/usr/share/nginx/static:ro
    ports:
      - 80:80
