version: '3'
services:
  bff:
    build: .
    container_name: 'bff'
    environment:
      - API_KEY
    volumes:
      - ./src:/app
      - ./static:/static
    stdin_open: true
    tty: true

  spa:
    build: spa_src
    container_name: 'spa'
    volumes:
      - ./spa_src/src/:/app/src
      - ./spa_src/public:/app/public
    stdin_open: true
    tty: true

  nginx:
    container_name: 'nginx'
    image: 'nginx'
    depends_on:
      - bff
      - spa
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./static:/usr/share/nginx/static:ro
    ports:
      - 80:80
