version: '3'
services:
  bff:
    build: .
    container_name: 'bff'
    environment:
      - API_KEY
      - API_HOST
    volumes:
      - ./src:/app
      - ./static:/static
    stdin_open: true
    tty: true

  spa:
    build: spa_src
    container_name: 'spa'
    volumes:
      - ./spa_src/src/:/app/src
      - ./spa_src/public:/app/public
    stdin_open: true
    tty: true

  api:
    build: mock_api
    container_name: 'api'
    volumes:
      - ./mock_api/:/app
    stdin_open: true
    tty: true

  nginx:
    container_name: 'nginx'
    image: 'nginx'
    depends_on:
      - bff
      - spa
      - api
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./static:/usr/share/nginx/static:ro
      - ./mock_api/cache:/usr/share/nginx/content:ro
    ports:
      - 80:80
